### ISSUE TITLE
Screensaver of display off option

### ISSUE THREAD

**Issue by rippiedoos** [pimoroni/mopidy-pidi#10]
I'm wondering if there is an option to shut down the display somehow, maybe on a regular basis?
If I now turn off the Pi by running the shutdown command, the display keeps the last state it has, including the backlight.

Could it be possible to disable the backlight if Mopidy-pidi-plugin stops? And how about disabling the backlight after 5 minutes of inactivity (or some setting in the pidi-plugin-config). This save the backlight and hopefully the ~~OLED~~ high quality IPS LCD itself so it doesn't burn out over time.

Great work on the plugin and the Pirate Audio part itself!

**Comment by Gadgetoid** [comment]
It's actually a *really good* IPS LCD, not an OLED :D - we obviously pick our display parts well!

But- yes- ideally the display should turn off when Mopidy shuts down or the plugin stops- looking into it.

**Comment by Gadgetoid** [comment]
I've released new versions- if you `sudo pip3 install --upgrade pidi-display-st7789 mopidy-pidi` you should get a version that turns off the display when Mopidy exits.

**Comment by rippiedoos** [comment]
Of course, I should have read the specs one more time before creating this issue...

Thanks for the quick fix. I will try it in the next week and will let you know how it turns out. I hope this will not wear out the LCD over time because I'm sure my daughter will forget turning this thing off when she goes to sleep. A shutdown-command in crontab will do the trick and this will nicely dim the display.

**Comment by Gadgetoid** [comment]
I think it's possible to add some display dimming after a timeout, but I think that's more useful for reducing brightness (and thus bothersome lights in the house) when it's not in use than saving the display. I think a bunch of people would appreciate the feature either way so it's probably worth keeping this issue opening and looking into it.

**Comment by rippiedoos** [comment]
My idea about this feature would be to poll the status, the same way the current song is now polled. Something in the line of
```
self.dimming_timeout = self.config["pidi"]["dimming_timeout"]
self.dimming_percent = self.config["pidi"]["dimming_percent"]

if self.state != 'play':
    if self._timer >= self.dimming_timeout:
        self._display.dim(self.dimming_percent) unless self.dimming_timeout
```
So setting dimming_timeout to 0 will disable dimming.

**Comment by Fabiandelete** [comment]
> My idea about this feature would be to poll the status, the same way the current song is now polled. Something in the line of
> 
> ```
> self.dimming_timeout = self.config["pidi"]["dimming_timeout"]
> self.dimming_percent = self.config["pidi"]["dimming_percent"]
> 
> if self.state != 'play':
>     if self._timer >= self.dimming_timeout:
>         self._display.dim(self.dimming_percent) unless self.dimming_timeout
> ```
> 
> So setting dimming_timeout to 0 will disable dimming.

Did you get this to work? And if so, could you explain how to set it up? And is it possible to get it to work with PiDi Spotify?

**Comment by rippiedoos** [comment]
Nope, didn't get around to get this to work. The piece of code in that comment was pseudo-code. Something like that should work but I haven't implemented it.

**Comment by snizzleorg** [comment]
I also would appreciate if the display would turn off if nothing is playing for 5 min or so. Would make it possible to use it in the bedroom ;-)

**Comment by issDaemon** [comment]
Configurable dimming would be a great feature. As above, it would make it useable in environments that are meant to be dark as well as save energy for portable applications.

**Comment by kokosowy** [comment]
Hi all! I hope this feature would be included. LCD is very bright, which is not cool when lights are turned off in the evening. It'd be awesome to have a parameter to control dim of display. @Gadgetoid did you considered that pull request?
