### ISSUE TITLE
Displaying stations names and track being streamed

### ISSUE THREAD

**Issue by chileno01** [pimoroni/mopidy-pidi#11]
There are several extensions for mopidy that let you listen to internet radios such as TuneIn or RadioNet.
I think it would be great if mopidy-pidi was able to display the name of the station and the track being streamed just like it does when playing local files.

**Comment by Gadgetoid** [comment]
TuneIn, at least, should already display station name and track. We currently don't implement `stream_title_changed` though, so I wonder if that prevents the song title updating as the stream progresses.
