### ISSUE TITLE
Pirate Audio LCD does not update when track changes when playing a Radio Stream

### ISSUE THREAD

**Issue by quattrofoto** [pimoroni/mopidy-pidi#13]
Hi,

I have a RPi Zero W with the Pirate Audio Phat (screen, buttons and amp).  I have installed all as per the instructions set out on the product page exactly.  However I do not use a Spotify account - I only use live radio streams and podcasts.  The buttons are working fine, and the display is working but it does not update the track info when the track changes whilst I am playing a radio stream - it just displays the name of the track that happened to be playing when I first started the stream.  Any ideas?

**Comment by Gadgetoid** [comment]
This may be because the change that implemented this has not yet made it to a release: https://github.com/pimoroni/mopidy-pidi/compare/v1.0.2...master

**Comment by Gadgetoid** [comment]
Try `sudo pip3 install --upgrade mopidy-pidi` and see if the new release works for you.

**Comment by quattrofoto** [comment]
Thanks for your swift answer, much appreciated.

I tried the above, and yes it kind of works...ish.  The track title does appear to update as it should during radio streams, that is if I can get a radio stream to actually play.  The new release of mopidy-pidi seems to have broken my system.  I can only get radio stations to play very occasionally - before trying this everything worked seamlessly (apart from the original lack of track name updates) but not anymore.  Whether I click on the stream in Iris or if I use the physical buttons the system is completely unresponsive 95% of the time.  Clicking on a playlist of stations just locks the entire system and nothing works at all until I reboot.  To reiterate, everything was fine before the update of mopidy-pidi.  Looks like I'm going to have to start from scratch again and just live with the lack of track name updates until the issue is fixed.

Thanks again for your help.
