### ISSUE TITLE
"Extension disabled due to config errors" when "idle_timeout" parameter is added?

### ISSUE THREAD

**Issue by miskor-bgd** [pimoroni/mopidy-pidi#20]
Hi all,

Fresh install as of today, new to mopidy

In order to enable idle timeout for pirate audio display I am editing mopidy config file here:

/etc/mopidy/mopidy.conf

and adding this line to [pidi] section:

idle_timeout = 60

But, then mopidy reports "Extension disabled due to config errors"!

Please advise how to fix... Thanks!

**Comment by Gadgetoid** [comment]
I don't believe this has been released yet, I'll need to test and release a new version of mopidy-pidi for this config option to be available.

**Comment by Gadgetoid** [comment]
I've released new versions of pidi-display-st7789 and mopidy-pidi, you should update both with something like:

```
sudo python3 -m pip install --upgrade pidi-display-st7789 mopidy-pidi
````

**Comment by miskor-bgd** [comment]
Thanks, will try in the afternoon and let you know if it works

**Comment by miskor-bgd** [comment]
So far it works well, display is turned off after specific number of seconds - thank you very much for this fix, it was needed...

**Comment by miskor-bgd** [comment]
Uh oh - I was too fast, it is not working well, when display is dimmed after idle timeout it will not wake up when any button is pressed, so display remains dark until mopidy server is restarted

**Comment by miskor-bgd** [comment]
Wait - play/pause and next buttons works OK and it will wake display but volume up/down does not!
