### ISSUE TITLE
Trouble installing: "No matching distribution found for Mopidy-PiDi"

### ISSUE THREAD

**Issue by danielo515** [pimoroni/mopidy-pidi#22]
Hello.
I am trying to install mopidy-pidi using the install script of mopidy. However, I am getting the following error:

```
Installing Pirate Audio plugins...
Collecting Mopidy-PiDi
  Could not find a version that satisfies the requirement Mopidy-PiDi (from versions: )
No matching distribution found for Mopidy-PiDi
```

I am using python 3.5 on a raspberrypi that has octopi installed (which I suppose uses raspbian).
Regards

**Comment by danielo515** [comment]
By the way, I[ am using the audio AMP shimp, ](https://shop.pimoroni.com/products/audio-amp-shim-3w-mono-amp)so maybe this library is not needed?

**Comment by Gadgetoid** [comment]
You shouldn't need this library with AMP SHIM, since it's for displaying album art on a screen.

New-ish versions of Mopidy require Python >= 3.7, so you're going to have some trouble installing on 3.5. You'll need a newer OS.

**Comment by danielo515** [comment]
Thank you.
I just ran the installation script on another raspberry pi and had no problems.
So this was not a problem before (because it was not needed) and it is not a problem now.

Regards
