### ISSUE TITLE
Question? Possible to turn the display 90°

### ISSUE THREAD

**Issue by 735751363r** [pimoroni/mopidy-pidi#24]

**Comment by Gadgetoid** [comment]
Yup, `rotation` is right there in the config:

https://github.com/pimoroni/mopidy-pidi/blob/master/mopidy_pidi/ext.conf#L4

This ends up in the `[pidi]` section of mopidy.conf where you should be able to tweak it.

**Comment by 735751363r** [comment]
Hi everyone. Right now I am using a very similar setup with Volumio und Plugins for GPIO Buttons (I`m usnig 4) and MPD Oled Display Build in the wall as an Jukebox and Spotify connect player Roomwise. I´m not very happy, because it is sometimes very buggy!
Now I found the Pirate audio which does eventually the same thing (Display and Buttons) Spotify Integration as well.
But in my case in one Room there is my Setup not build in  vertically! So I`m curios if it is possible to turn the display and maybe solder external buttons to the board?

**Comment by 735751363r** [comment]
> Yup, `rotation` is right there in the config:
> 
> https://github.com/pimoroni/mopidy-pidi/blob/master/mopidy_pidi/ext.conf#L4
> 
> This ends up in the `[pidi]` section of mopidy.conf where you should be able to tweak it.

Whow thank you for this FAST response :D That sounds quite promising!!!
