### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by arthurlutz** [pimoroni/mopidy-pidi#8]
Hey, project looks interresting, any chance of showing a screenshot or photo of the display running in the README ?

**Comment by Gadgetoid** [comment]
I don't see any reason why not! I mean... it's only going to help us sell more displays right? 😆 

This plugin currently supports our own displays from the Pirate Audio range- https://shop.pimoroni.com/collections/pirate-audio

But there's no reason it couldn't support others. (and I welcome that, insofar as I can spare the time to test/merge contributions)

**Comment by Gadgetoid** [comment]
Sorted! Thank you for the suggestion.
