### ISSUE TITLE
PiDi not refreshing screen on certain track changes (YouTube and TuneIn so far)

### ISSUE THREAD

**Issue by TrollDecker** [pimoroni/mopidy-pidi#9]
Heyo,

I've noticed the Pirate-Audio display wasn't updating when starting a youtube video (via `mopidy-youtube`) or a radio station (via `mopidy-tunein`), staying frozen on its previous screen until the buttons on the HAT were pressed or a track from another source was selected, after which it would update properly.

Upon looking at the logs, it looks like `mopidy-pidi` is running into a bit of a roadblock as in both cases the YouTube and TuneIn plugins are providing a `NoneType` to values that `mopidy-pidi` is expecting to be a specific type.

In the case of the TuneIn plugin, mopidy-pidi is throwing this error:
```
Feb 14 23:23:48 pirate-audio mopidy[844]: ERROR    [PiDiFrontend-15] mopidy.listener Triggering event failed: track_playback_started(tl_track)
Feb 14 23:23:48 pirate-audio mopidy[844]: Traceback (most recent call last):
Feb 14 23:23:48 pirate-audio mopidy[844]:   File "/usr/local/lib/python3.7/dist-packages/mopidy/listener.py", line 40, in on_event
Feb 14 23:23:48 pirate-audio mopidy[844]:     getattr(self, event)(**kwargs)
Feb 14 23:23:48 pirate-audio mopidy[844]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_pidi/frontend.py", line 110, in track_playback_started
Feb 14 23:23:48 pirate-audio mopidy[844]:     self.update_track(tl_track.track, 0)
Feb 14 23:23:48 pirate-audio mopidy[844]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_pidi/frontend.py", line 137, in update_track
Feb 14 23:23:48 pirate-audio mopidy[844]:     elapsed=float(time_position), length=float(track.length)
Feb 14 23:23:48 pirate-audio mopidy[844]: TypeError: float() argument must be a string or a number, not 'NoneType'
```

(It's probably tripping over at `length=float(track.length)` because radio stations, of course)

And with the YouTube plugin, the error seems to be:

```
Feb 14 23:30:16 pirate-audio mopidy[844]: ERROR    [PiDiFrontend-15] mopidy.listener Triggering event failed: track_playback_started(tl_track)
Feb 14 23:30:16 pirate-audio mopidy[844]: Traceback (most recent call last):
Feb 14 23:30:16 pirate-audio mopidy[844]:   File "/usr/local/lib/python3.7/dist-packages/mopidy/listener.py", line 40, in on_event
Feb 14 23:30:16 pirate-audio mopidy[844]:     getattr(self, event)(**kwargs)
Feb 14 23:30:16 pirate-audio mopidy[844]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_pidi/frontend.py", line 110, in track_playback_started
Feb 14 23:30:16 pirate-audio mopidy[844]:     self.update_track(tl_track.track, 0)
Feb 14 23:30:16 pirate-audio mopidy[844]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_pidi/frontend.py", line 148, in update_track
Feb 14 23:30:16 pirate-audio mopidy[844]:     if image.height >= 240 and image.width >= 240:
Feb 14 23:30:16 pirate-audio mopidy[844]: TypeError: '>=' not supported between instances of 'NoneType' and 'int'
```

(I'm guessing this plugin doesn't actually fetch a cover image (yet) and that's what's causing this?)

**Comment by TrollDecker** [comment]
Update. Seems the error caused by TuneIn is also caused by streams in general.

**Comment by Gadgetoid** [comment]
I must admit I never thought to test with any of these plugins, but it'd be nice if we could support them.

I think we're all still reeling from Mopidy 3.x (and I'm absurdly busy with 32Blit) so I'm hesitant to look into this too quickly, but it's on my TODO!

**Comment by jchmielniak** [comment]
It is caused by 'track.length = None'
'dirty' fix in Line  276: 
elapsed=float(time_position), length=float(track.length or 100)

**Comment by Gadgetoid** [comment]
Thank you- I wonder if the track length is relayed by another mechanism I can hook into. Will try and get this tested and added for now, though.

**Comment by Gadgetoid** [comment]
Okay having consulted the documentation (ha!) it looks like `None` is a valid value for `Track.length` and thus your dirty fix is probably less dirty than you might think :D

Relevant documentation: https://docs.mopidy.com/en/latest/api/models/#mopidy.models.Track

**Comment by TrollDecker** [comment]
Gave it a shot and can confirm it's now updating the screen correctly. :slightly_smiling_face:  :+1:

**Comment by Gadgetoid** [comment]
Woohoo! Thank you.

**Comment by jchmielniak** [comment]
The 'title' (in stream) won't update. I traced it back to pidi_display_pil. Screen will redraw only by 
 progress or status change. I will try to fix it there and then I'll send a small fix for frontend.py

**Comment by Gadgetoid** [comment]
Ah yes, `pidi_display_pil` has an alarming amount of code to try and prevent unecessary redraw to avoid high CPU load/SPI bus throughput. I'm not surprised by this!

Thanks for digging into it.
